CLIENT_SOCKET_PORT = 5000
CLIENT_SOCKET_HOST = "localhost"

SERVER_SOCKET_PORT = 5000
SERVER_SOCKET_HOST = "0.0.0.0"

MQTT_PORT = 1883
MQTT_HOST = "localhost"
MQTT_CLIENT_ID = "atividade-extensao"
MQTT_GEOLOCATION_TOPIC = "/vehicle-position"

NETWORK_NAME = ""
NETWORK_PASSWORD = ""

GPS_TX_PIN = 0
GPS_RX_PIN = 0

LOCATION_SERVICE_URL = "https://location.services.mozilla.com/v1/geolocate"
LOCATION_SERVICE_TOKEN = ""
